# Aplicação
spring.application.name=saude-cardiaca-api
server.address=0.0.0.0
server.port=8080

# Banco de dados H2 (desenvolvimento)
spring.datasource.url=jdbc:h2:mem:saudecardiaca
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=admin
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# JWT
jwt.secret=AL7bYKEBdhEEM5wCscu4L1NkimLaaacjjMHVtP6b0vX
jwt.expiration-ms=86400000

# Swagger / OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Gemini
gemini.api-key=${GEMINI_API_KEY:}
gemini.model=gemini-2.5-flash
gemini.timeout-ms=10000

# Email (Gmail SMTP) - configure com suas credenciais
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:kaiocarvalho558@gmail.com}
spring.mail.password=${MAIL_PASSWORD:iydu juid xmih vwew}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Reset de senha
password.reset.code.expiry-minutes=15
